version: "3"
services:
  wazigate-edge:
    container_name: wazigate-edge
    image: waziup/wazigate-edge
    ports:
      - "80:80"
      - "1883:1883"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/go/src/wazigate-edge

    environment:
      - WAZIUP_HTTP_ADDR=:80
      # - WAZIUP_HTTPS_ADDR=:4443
      # - WAZIUP_MQTT_ADDR=:1883
      # - WAZIUP_MQTTS_ADDR=:8883
      # - WAZIUP_TLS_CRT =   # TLS Cert File (.crt)
      # - WAZIUP_TLS_KEY =   # TLS Key File (.key)
      - WAZIUP_MONGO=localhost:27017
      - WAZIUP_CLOUDS_FILE=/root/conf/clouds.json
    network_mode: host
    # depends_on:
    #   - wazigate-mongo
    healthcheck:
      test: curl --fail http://localhost:880/device || exit 1
      interval: 30s
      retries: 10 # Will try for 5 minutes
#    restart: always
